$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: model
command: >-
  python train.py
  --training_data ${{ inputs.training_data }}
  --reg_rate ${{ inputs.reg_rate }}
inputs:
  training_data: 
    type: uri_folder 
    path: azureml:diabetes-prod-folder:1
  reg_rate: 0.03
environment: azureml:train-env@latest
compute: computee
experiment_name: mlops-experiment
display_name: prod-model-training-job
description: A machine learning classification model training job.